### ISSUE TITLE
Handle disconnect / ping timeouts

### ISSUE THREAD

**Issue by ear** [tsoding/HyperNerd#209] opened 2018-08-16 23:14 UTC
I changed network (wired -> wifi) and the bot didn't understand that not receiving `Ping`s from the server was a bad thing.

I guess for that reason it never figured out it wasn't connected anymore and didn't reconnect after a while. But I think it should.

**Comment by rexim** [comment] 2018-08-17 07:31
Duplicate of #143

**Closed** 2018-08-17 07:31 UTC
