### ISSUE TITLE
youtube link regex is broken

### ISSUE THREAD

**Issue by PaprikaX33** [tsoding/HyperNerd#791] opened 2019-09-23 11:35 UTC
The youtube link finder regex on `!friday` command is broken when the first character of the video id is `-`

**Comment by rexim** [comment] 2019-09-23 13:47
@PaprikaX33 duplicate of #715 sorry

**Closed by rexim** 2019-09-23 13:47 UTC
Labels: duplicate

**Comment by PaprikaX33** [comment] 2019-09-23 13:53
Whoops, sorry. I missed it when searching for possible duplicates

**Comment by rexim** [comment] 2019-09-23 14:00
@PaprikaX33 don't worry, the wording is completely different. No surprise it was hard to find. :smiley:
